export const CategoryType = {
    FETCH_CATEGORIES_REQUEST : 'FETCH_CATEGORIES_REQUEST',
    FETCH_CATEGORIES_SUCCESS : 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE : 'FETCH_CATEGORIES_FAILURE'
}

export const PostType = {
    FETCH_POSTS_REQUEST : 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS : 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE : 'FETCH_POSTS_FAILURE',

    FETCH_POSTS_BY_CATEGORY_REQUEST : 'FETCH_POSTS_BY_CATEGORY_REQUEST',
    FETCH_POSTS_BY_CATEGORY_SUCCESS : 'FETCH_POSTS_BY_CATEGORY_SUCCESS',
    FETCH_POSTS_BY_CATEGORY_FAILURE : 'FETCH_POSTS_BY_CATEGORY_FAILURE',

    FETCH_POST_DETAIL_REQUEST : 'FETCH_POST_DETAIL_REQUEST',
    FETCH_POST_DETAIL_SUCCESS : 'FETCH_POST_DETAIL_SUCCESS',
    FETCH_POST_DETAIL_FAILURE : 'FETCH_POST_DETAIL_FAILURE',

    ADD_POST_REQUEST : 'ADD_POST_REQUEST',
    ADD_POST_SUCCESS : 'ADD_POST_SUCCESS',
    ADD_POST_FAILURE : 'ADD_POST_FAILURE',

    EDIT_POST_REQUEST : 'EDIT_POST_REQUEST',
    EDIT_POST_SUCCESS : 'EDIT_POST_SUCCESS',
    EDIT_POST_FAILURE : 'EDIT_POST_FAILURE',

    DELETE_POST_REQUEST : 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS : 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE : 'DELETE_POST_FAILURE',

    VOTE_POST_REQUEST : 'VOTE_POST_REQUEST',
    VOTE_POST_SUCCESS : 'VOTE_POST_SUCCESS',
    VOTE_POST_FAILURE : 'VOTE_POST_FAILURE',

    SORT_BY_TYPE : 'SORT_BY_TYPE'
    
}

export const CommentType = {
    FETCH_COMMENTS_REQUEST : 'FETCH_COMMENTS_REQUEST',
    FETCH_COMMENTS_SUCCESS : 'FETCH_COMMENTS_SUCCESS',
    FETCH_COMMENTS_FAILURE : 'FETCH_COMMENTS_FAILURE',

    FETCH_COMMENT_REQUEST : 'FETCH_COMMENT_REQUEST',
    FETCH_COMMENT_SUCCESS : 'FETCH_COMMENT_SUCCESS',
    FETCH_COMMENT_FAILURE : 'FETCH_COMMENT_FAILURE',

    POST_COMMENT_REQUEST : 'POST_COMMENT_REQUEST',
    POST_COMMENT_SUCCESS : 'POST_COMMENT_SUCCESS',
    POST_COMMENT_FAILURE : 'POST_COMMENT_FAILURE',

    UPDATE_COMMENT_REQUEST : 'UPDATE_COMMENT_REQUEST',
    UPDATE_COMMENT_SUCCESS : 'UPDATE_COMMENT_SUCCESS',
    UPDATE_COMMENT_FAILURE : 'UPDATE_COMMENT_FAILURE',

    DELETE_COMMENT_REQUEST : 'DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_SUCCESS : 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILURE : 'DELETE_COMMENT_FAILURE',

    VOTE_COMMENT_REQUEST : 'VOTE_COMMENT_REQUEST',
    VOTE_COMMENT_SUCCESS : 'VOTE_COMMENT_SUCCESS',
    VOTE_COMMENT_FAILURE : 'VOTE_COMMENT_FAILURE'
}

export const SORT_BY_TYPE = 'SORT_BY_TYPE'
